### PR TITLE
Correct guess_mime_type deprecation warning

### LINKED ISSUE #49: Incorrect deprecation warning
```
warning: use of deprecated item 'mime_guess::guess_mime_type': Use `from_path(path).or_octet_stream()` instead
  --> src/lib\data\image.rs:31:20
   |
31 |         let mime = guess_mime_type(path);
   |
```

There is no `.or_octet_stream`
Guess it was changed later to `first_or_octet_stream`

### PR DESCRIPTION
**Pull request by DoumanAsh**
Fixes  #49

### CODE REVIEW

**Comment by abonander** [comment]
Thanks. Do you want to get these other deprecation messages as well?

* Should be `from_path(path).first_raw()`: https://github.com/abonander/mime_guess/blob/master/src/lib.rs#L319
* Should be `from_ext(search_ext).first_or_octet_stream()`: https://github.com/abonander/mime_guess/blob/master/src/lib.rs#L336
* Should be `from_ext(search_ext).first_raw()`: https://github.com/abonander/mime_guess/blob/master/src/lib.rs#L359

**Comment by DoumanAsh** [comment]
@abonander Went through all deprecated method and updated

File: src/lib.rs [hunk 1]
```diff
@@ -356,7 +356,7 @@ pub fn get_mime_type_opt(search_ext: &str) -> Option<Mime> {
 /// Returns `None` if `search_ext` is empty or an associated extension was not found.
 #[deprecated(
     since = "2.0.0",
-    note = "use `from_ext(search_ext).first_as_str()` instead"
+    note = "use `from_ext(search_ext).first_raw()` instead"
 )]
 pub fn get_mime_type_str(search_ext: &str) -> Option<&'static str> {
     from_path(search_ext).first_raw()
```
Comment (abonander) [inline src/lib.rs]: Oops, looks like I made a mistake here which I missed because I removed the tests for the deprecated functions. This should use `from_ext()` like the deprecation message, not `from_path()`.

**Comment by abonander** [comment]
If you'd like to fix that bug I pointed out, go ahead. Otherwise this is good to merge when the build passes.

File: src/lib.rs (hunk 1 above)
Comment (DoumanAsh) [reply src/lib.rs]: oh really, I didn't notice mistake at first, will correct

**Comment by DoumanAsh** [comment]
Corrected impl as well

**Comment by abonander** [comment]
Excellent work, thanks. This is good to merge when it passes.

**Comment by abonander** [comment]
Published as `2.0.1`.
